// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'package:auto_json_serialize_example/building.dart' as x0 show Building;
import 'package:auto_json_serialize_example/floor.dart' as x1 show Floor;
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// ignore_for_file: invalid_language_version_override
// No output from reflectable, there is no `main`.
final buildingAdapter = JsonMapperAdapter(
  title: 'buildingAdapter',
  url: 'package:auto_json_serialize_example/building.dart',
  valueDecorators: {
    typeOf<List<x0.Building>>(): (value) => value.cast<x0.Building>(),
    typeOf<Set<x0.Building>>(): (value) => value.cast<x0.Building>(),
    typeOf<List<x1.Floor>>(): (value) => value.cast<x1.Floor>(),
    typeOf<Set<x1.Floor>>(): (value) => value.cast<x1.Floor>()
},
  enumValues: {

});

Future<JsonMapper> initializeJsonMapperAsync({Iterable<JsonMapperAdapter> adapters = const []}) => Future(() => initializeJsonMapper(adapters: adapters));

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  
  [...adapters, buildingAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}