// This file has been generated by the dart_json_mapper package.
// https://github.com/k-paxian/dart-json-mapper
// @dart = 2.12
import 'package:auto_json_serialize_example/floor.dart' as x0 show Floor;
import 'package:dart_json_mapper/dart_json_mapper.dart' show JsonMapper, JsonMapperAdapter, typeOf;

// ignore_for_file: invalid_language_version_override
// No output from reflectable, there is no `main`.
final floorAdapter = JsonMapperAdapter(
  title: 'floorAdapter',
  url: 'package:auto_json_serialize_example/floor.dart',
  valueDecorators: {
    typeOf<List<x0.Floor>>(): (value) => value.cast<x0.Floor>(),
    typeOf<Set<x0.Floor>>(): (value) => value.cast<x0.Floor>()
},
  enumValues: {

});

Future<JsonMapper> initializeJsonMapperAsync({Iterable<JsonMapperAdapter> adapters = const []}) => Future(() => initializeJsonMapper(adapters: adapters));

JsonMapper initializeJsonMapper({Iterable<JsonMapperAdapter> adapters = const []}) {
  
  [...adapters, floorAdapter].forEach((x) => JsonMapper().useAdapter(x));
  return JsonMapper();
}